name: Alpha Patch

on:
  push:
    tags:
      - "v0.0.*"

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1 
        with:
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          override: true
          rustflags: ""
          components: rust-src

      - name: Install cross
        run: cargo install cross

      - name: Build for aarch64
        run: cross build --target aarch64-unknown-linux-gnu --release

      - name: Prepare release archive
        run: |
          mkdir -p release
          cp target/aarch64-unknown-linux-gnu/release/cyborg-miner release/
          cp cyborg-agent release/
          cp scripts/setup.sh release/
          chmod +x release/cyborg-miner release/cyborg-agent release/setup.sh
          tar -czvf cyborg-miner-linux-aarch64.tar.gz -C release .

      - name: Create GitHub Release and upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cyborg-miner-linux-aarch64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
